### ISSUE TITLE
Crash when diminishing delta time samples

### ISSUE THREAD

**Issue by Kouros26** [karnkaul/levk#15]
![image](https://github.com/karnkaul/levk/assets/65140699/8c79c038-09ec-49b6-8db9-7d550b7aa57f)

It doesn't crash based on the value, it crashes when you slide it too fast to the left lol

**Comment by karnkaul** [comment]
Hmm, I can't seem to reproduce the issue, at least on Linux:

https://github.com/karnkaul/levk/assets/16272243/b2833ac4-14fb-403d-a9f7-0af5d9e532d4

**Comment by Kouros26** [comment]
https://github.com/karnkaul/levk/assets/65140699/678b7b30-38c9-419f-92b6-5311bbba10f9

It crashes every time on windows, here's a part of the error message that pops up

![image](https://github.com/karnkaul/levk/assets/65140699/74db9d8d-600f-4eba-8fe0-ddd3bb9c967b)

**Comment by karnkaul** [comment]
Definitely looks like a bug, will take a closer look, thanks!
